# Generated by Django 5.1.3 on 2024-11-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Project Image')),
            ],
        ),
    ]
